export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git docker docker-compose nvm)
source $ZSH/oh-my-zsh.sh
path+=("/opt/homebrew/bin")
path+=("$HOME/Code/bin")
path+=("/opt/homebrew/opt/node@20/bin")
export GOPATH="$HOME/Code/go"
path+=("$GOPATH/bin")
cd $HOME/Code
