export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussel"
plugins=(git docker docker-compose nvm)
source $ZSH/oh-my-zsh.sh
path+=("/opt/homebrew/bin")
path+=("$HOME/Code/bin")
export GOPATH="$HOME/Code/go"
